# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN yarn install

# Copy the rest of your application code to the container
COPY . .

# Expose a port (e.g., 3000) that your Node.js app will listen on
EXPOSE 3000

# Define the command to run your Node.js app
CMD ["yarn", "dev"]
